---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      volumes:
        - name: config-radarr
          persistentVolumeClaim:
            claimName: pvc-config-radarr
        - name: downloads
          persistentVolumeClaim:
            claimName: pvc-stack-downloads
        - name: movies
          persistentVolumeClaim:
            claimName: pvc-stack-movies

      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:latest
          env:
            - name: PUID
              value: '1000'
            - name: PGID
              value: '1000'
            - name: TZ
              value: Etc/UTC
          ports:
            - containerPort: 7878
              name: radarr
          resources:
            requests:
              cpu: 1000m
              memory: 2Gi
            limits:
              cpu: 2000m
              memory: 4Gi
          securityContext:
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: config-radarr
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: movies
              mountPath: /movies
