---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-config-radarr
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: nfs-radarr-config
  storageClassName: ""
