---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-stack-downloads
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  volumeName: nfs-stack-downloads
  storageClassName: ""
