---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  labels:
    app: radarr
    service: server
spec:
  selector:
    app: radarr
  ports:
    - protocol: TCP
      port: 7878
      targetPort: 7878
