---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  labels:
    app: radarr
    service: server
spec:
  selector:
    app: radarr
  type: {{ .Values.service.type }}
  ports:
    - name: radarr
      protocol: TCP
      port: 7878
      targetPort: 7878
