apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- clusterrolebinding.yaml
- configmap.yaml
- secret.yaml
- service.yaml
- statefulset.yaml

patchesJson6902:
  # - target:
  #     version: v1
  #     kind: Service
  #     name: satisfactory
  #   patch: |-
  #     - op: replace
  #       path: /spec/ports/0/nodePort
  #       value: 30777
  #     - op: replace
  #       path: /spec/ports/1/nodePort
  #       value: 31000
  #     - op: replace
  #       path: /spec/ports/2/nodePort
  #       value: 31777
  - target:
      version: apps/v1
      kind: StatefulSet
      name: satisfactory
    patch: |-
      - op: add
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: lvms-vg1
