---
apiVersion: v1
kind: Service
metadata:
  name: satisfactory
  namespace: satisfactory
spec:
  selector:
    app: game
    game: satisfactory
  type: NodePort
  ports:
  - name: game
    port: 7777
    targetPort: 7777
    nodePort: 7777
    protocol: UDP
  - name: beacon
    port: 15000
    targetPort: 15000
    nodePort: 15000
    protocol: UDP
  - name: query
    port: 15777
    targetPort: 15777
    nodePort: 15777
    protocol: UDP
