{{- if .Values.ingress.enable }}
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  annotations:
    route.openshift.io/termination: edge
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/hostname: jellyfin.hknlab.io
    external-dns.alpha.kubernetes.io/target: dyn4.hknlab.io
    # cert-manager.io/private-key-rotation-policy: always
    # acme.cert-manager.io/http01-ingress-class: openshift-default
  name: jellyfin
  namespace: jellyfin
spec:
  ingressClassName: openshift-default
  tls:
    - secretName: jellyfin-tls
      hosts:
        - jellyfin.hknlab.io
  rules:
    - host: jellyfin.hknlab.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyfin
                port:
                  number: 8096
{{- end }}
