{{- if .Values.storage.incomplete.enabled }}
{{- if not .Values.storage.incomplete.existingClaimName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-incomplete" .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes: {{ .Values.storage.incomplete.accessModes }}
  resources:
    requests:
      storage: {{ .Values.storage.incomplete.storageSize }}
  volumeName: {{ .Values.storage.incomplete.existingVolumeName | quote }}
  storageClassName: {{ .Values.storage.incomplete.storageClassName | quote }}
{{- end }}
{{- end }}
