---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sabnzbd.fullname" . }}
  labels:
    {{- include "sabnzbd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: sabnzbd
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: sabnzbd
  selector:
    {{- include "sabnzbd.selectorLabels" . | nindent 4 }}
