---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lidarr
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      volumes:
        - name: config-lidarr
          persistentVolumeClaim:
            claimName: pvc-config-lidarr
        - name: downloads
          persistentVolumeClaim:
            claimName: pvc-stack-downloads
        - name: music
          persistentVolumeClaim:
            claimName: pvc-stack-music

      containers:
        - name: lidarr
          image: lscr.io/linuxserver/lidarr:latest
          env:
            - name: PUID
              value: '1000'
            - name: PGID
              value: '1000'
            - name: TZ
              value: Etc/UTC
          ports:
            - containerPort: 8686
              name: lidarr
          resources:
            requests:
              cpu: 1000m
              memory: 2Gi
            limits:
              cpu: 2000m
              memory: 4Gi
          securityContext:
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: config-lidarr
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: music
              mountPath: /music
