{{- if .Values.storage.music.enabled }}
{{- if not .Values.storage.music.existingClaimName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-music" .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes: {{ .Values.storage.music.accessModes }}
  resources:
    requests:
      storage: {{ .Values.storage.music.storageSize }}
  volumeName: {{ .Values.storage.music.existingVolumeName | quote }}
  storageClassName: {{ .Values.storage.music.storageClassName | quote }}
{{- end }}
{{- end }}
