{{- if .Values.ingress.enable }}
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  annotations: {{ .Values.ingress.annotations }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - jellyseerr.hknlab.io
      secretName: jellyseerr-tls
  rules:
    - host: jellyseerr.hknlab.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyseerr
                port:
                  number: 5055
{{- end }}
