---
apiVersion: v2
name: 7dtd
version: 0.1.0
appVersion: 0.4.4
description: 7 Days to Die is an open-world game that is a unique combination of first person shooter, survival horror, tower defense, and role-playing games.
keywords:
  - 7dtd
  - 7 Days to Die
  - game
  - horror
  - steam
home: https://7daystodie.com/
icon: https://user-images.githubusercontent.com/6136865/29045114-9ae8e510-7bc2-11e7-8487-19552001aafd.png
sources:
  - https://github.com/alexnuttinck/helm-7dtd
maintainers:
  - name: alexnuttinck
    url: https://github.com/alexnuttinck
