---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: obico-web
  namespace: obico
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obico-web
  template:
    metadata:
      labels:
        app: obico-web
    spec:
      containers:
      - name: web
        image: ghcr.io/thespaghettidetective/obico-server/server:0.1.0-release.1.4241
        imagePullPolicy: Always
        command: 
          - sh 
          - -c 
          - 'python manage.py migrate && python manage.py collectstatic -v 2 --noinput && daphne -b 0.0.0.0 -p 3334 config.routing:application'
        envFrom:
        - configMapRef:
            name: obico-base
        - configMapRef:
            name: obico-web
        ports:
        - name: web
          containerPort: 3334
        resources:
          limits:
            cpu: 2000m
            memory: 8Gi
          requests:
            cpu: 1000m
            memory: 4Gi
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          allowPrivilegeEscalation: true
          runAsNonRoot: false
