---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: obico
  labels:
    app: obico-web
spec:
  type: ClusterIP
  selector:
    app: obico-web
  ports:
  - name: web
    protocol: TCP
    port: 3334
    targetPort: 3334

---
apiVersion: v1
kind: Service
metadata:
  name: ml-api
  namespace: obico
  labels:
    app: obico-ml-api
spec:
  type: ClusterIP
  selector:
    app: obico-ml-api
  ports:
  - name: ml-api
    protocol: TCP
    port: 3333
    targetPort: 3333
