---
apiVersion: v1
kind: Secret
metadata:
  name: tdarr-node-env
stringData:
  TZ: Etc/UTC
  PUID: '1000'
  PGID: '1000'
  nodeName: ''
  serverIP: {{ .Values.controller.ip | quote }}
  serverPort: {{ .Values.controller.port | quote }}
  inContainer: 'true'
  ffmpegVersion: '7'
  NVIDIA_DRIVER_CAPABILITIES: all
  NVIDIA_VISIBLE_DEVICES: all
