---
apiVersion: v1
kind: Secret
metadata:
  name: configarr
type: Opaque
stringData:
  secrets.yml: |
    SONARR_API_KEY: {{ .Values.secrets.sonarr.api_key | quote }}
    RADARR_API_KEY: {{ .Values.secrets.radarr.api_key | quote }}
