{{- if .Values.storage.downloads.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ default (printf "%s-downloads" .Release.Name) .Values.storage.downloads.existingClaimName }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes: {{ .Values.storage.downloads.accessModes }}
  resources:
    requests:
      storage: {{ .Values.storage.downloads.storageSize }}
  volumeName: {{ .Values.storage.downloads.existingVolumeName | quote }}
  storageClassName: {{ .Values.storage.downloads.storageClassName | quote }}
{{- end }}
