---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  labels:
    app: sonarr
    service: server
spec:
  selector:
    app: sonarr
  ports:
    - protocol: TCP
      port: 8989
      targetPort: 8989
