---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-palworld
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.16.100.11
    path: /volume1/games/palworld
  persistentVolumeReclaimPolicy: Retain
