---
apiVersion: v1
kind: Service
metadata:
  name: palworld
  namespace: palworld
spec:
  type: NodePort
  selector: 
    app: game
    game: palworld
  ports: 
    - name: game
      port: 8211
      targetPort: 8211
      nodePort: 30411
      protocol: UDP
    - name: query
      port: 8212
      targetPort: 8212
      nodePort: 30412
      protocol: UDP
