---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metube-downloads
spec:
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: nfs-metube-downloads
  storageClassName: ''
