# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: unifi-data
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi
#   volumeName: {{ .Values.storage.data.volumeName }}
#   storageClassName: {{ .Values.storage.data.storageClassName }}

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: unifi-log
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi
#   volumeName: {{ .Values.storage.log.volumeName }}
#   storageClassName: {{ .Values.storage.log.storageClassName }}

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: unifi-run
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi
#   volumeName: {{ .Values.storage.run.volumeName }}
#   storageClassName: {{ .Values.storage.run.storageClassName }}
