apiVersion: v1
kind: Service
metadata:
  name: {{ include "unifi.fullname" . }}
  labels:
    {{- include "unifi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.http.port }}
      protocol: TCP
      targetPort: http
    - name: https
      port: {{ .Values.service.https.port }}
      protocol: TCP
      targetPort: https
    - name: stun
      port: {{ .Values.service.stun.port }}
      protocol: UDP
      targetPort: stun
  selector:
    {{- include "unifi.selectorLabels" . | nindent 4 }}
