---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-config-prowlarr
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: nfs-prowlarr-config
  storageClassName: ""
