---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "satisfactory.fullname" . }}-config
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: "lvms-vg1"

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: {{ include "satisfactory.fullname" . }}-backups
# spec:
#   accessModes:
#   - ReadWriteMany
#   resources:
#     requests:
#       storage: 5Gi
#   volumeName: {{ default .Values.storage.backups.existingVolume "" }}
#   storageClassName: ""

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: {{ include "satisfactory.fullname" . }}-gamefiles
# spec:
#   accessModes:
#   - ReadWriteMany
#   resources:
#     requests:
#       storage: 10Gi
#   volumeName: {{ default .Values.storage.gamefiles.existingVolume "" }}
#   storageClassName: ""

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: {{ include "satisfactory.fullname" . }}-logs
# spec:
#   accessModes:
#   - ReadWriteMany
#   resources:
#     requests:
#       storage: 1Gi
#   volumeName: {{ default .Values.storage.logs.existingVolume "" }}
#   storageClassName: ""

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: {{ include "satisfactory.fullname" . }}-saved
# spec:
#   accessModes:
#   - ReadWriteMany
#   resources:
#     requests:
#       storage: 5Gi
#   volumeName: {{ default .Values.storage.saved.existingVolume "" }}
#   storageClassName: ""
