---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-env" .Release.Name }}
  namespace: {{ .Release.Namespace }}
stringData:
  TZ: Etc/UTC
  PUID: '0'
  PGID: '0'
  nodeName: {{ .Release.Name }}
  serverIP: '0.0.0.0'
  serverPort: '8266'
  webUIPort: '8265'
  internalNode: 'true'
  inContainer: 'true'
  ffmpegVersion: '7'
  NVIDIA_DRIVER_CAPABILITIES: all
  NVIDIA_VISIBLE_DEVICES: all
