---
apiVersion: v1
kind: Secret
metadata:
  name: tdarr-server-env
stringData:
  TZ: Etc/UTC
  PUID: '1000'
  PGID: '1000'
  nodeName: ''
  serverIP: '0.0.0.0'
  serverPort: '8266'
  webUIPort: '8265'
  internalNode: 'true'
  inContainer: 'true'
  ffmpegVersion: '7'
  NVIDIA_DRIVER_CAPABILITIES: all
  NVIDIA_VISIBLE_DEVICES: all
