apiVersion: v1
kind: Service
metadata:
  name: tdarr-server
  labels:
    {{- include "tdarr-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "tdarr-server.selectorLabels" . | nindent 4 }}
  ports:
    - name: webui
      protocol: TCP
      port: {{ .Values.service.webui.port }}
      targetPort: webui
    - name: server
      protocol: TCP
      port: {{ .Values.service.server.port }}
      targetPort: server
