---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      volumes:
        - name: config-bazarr
          persistentVolumeClaim:
            claimName: pvc-config-bazarr
        - name: movies
          persistentVolumeClaim:
            claimName: pvc-stack-movies
        - name: tv
          persistentVolumeClaim:
            claimName: pvc-stack-tv

      containers:
        - name: bazarr
          image: lscr.io/linuxserver/bazarr:latest
          env:
            - name: PUID
              value: '1000'
            - name: PGID
              value: '1000'
            - name: TZ
              value: Etc/UTC
            # - name: UMASK
            #   value: '002'
          ports:
            - name: bazarr
              containerPort: 6767
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            requests:
              cpu: 1000m
              memory: 2Gi
            limits:
              cpu: 2000m
              memory: 4Gi
          securityContext:
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: config-bazarr
              mountPath: /config
            - name: tv
              mountPath: /tv
            - name: movies
              mountPath: /movies
