{{- if .Values.storage.tv.enabled }}
{{- if not .Values.storage.tv.existingClaimName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-tv" .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes: {{ .Values.storage.tv.accessModes }}
  resources:
    requests:
      storage: {{ .Values.storage.tv.storageSize }}
  volumeName: {{ .Values.storage.tv.existingVolumeName | quote }}
  storageClassName: {{ .Values.storage.tv.storageClassName | quote }}
{{- end }}
{{- end }}
