---
apiVersion: v1
kind: Service
metadata:
  name: bazarr
  labels:
    app: bazarr
    service: server
spec:
  selector:
    app: bazarr
  ports:
    - protocol: TCP
      port: 6767
      targetPort: 6767
