---
apiVersion: v1
kind: Service
metadata:
  name: bazarr
  labels:
    app: bazarr
    service: server
spec:
  type: ClusterIP
  selector:
    app: bazarr
  ports:
    - name: bazarr
      protocol: TCP
      port: 6767
      targetPort: 6767
