---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omada-data
spec:
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: ''
  storageClassName: 'basic'

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omada-logs
spec:
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: ''
  storageClassName: 'basic'
