---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: readarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: readarr
  template:
    metadata:
      labels:
        app: readarr
    spec:
      volumes:
        - name: books
          persistentVolumeClaim:
            claimName: pvc-stack-books
        - name: config-readarr
          persistentVolumeClaim:
            claimName: pvc-config-readarr
        - name: downloads
          persistentVolumeClaim:
            claimName: pvc-stack-downloads

      containers:
        - name: readarr
          image: lscr.io/linuxserver/readarr:develop
          env:
            - name: PUID
              value: '1000'
            - name: PGID
              value: '1000'
            - name: TZ
              value: Etc/UTC
          ports:
            - containerPort: 8787
              name: readarr
          resources:
            requests:
              cpu: 1000m
              memory: 2Gi
            limits:
              cpu: 2000m
              memory: 4Gi
          securityContext:
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: books
              mountPath: /books
            - name: config-readarr
              mountPath: /config
            - name: downloads
              mountPath: /downloads
