{{- if .Values.storage.books.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ default (printf "%s-books" .Release.Name) .Values.storage.books.existingClaimName }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes: {{ .Values.storage.books.accessModes }}
  resources:
    requests:
      storage: {{ .Values.storage.books.storageSize }}
  volumeName: {{ .Values.storage.books.existingVolumeName | quote }}
  storageClassName: {{ .Values.storage.books.storageClassName | quote }}
{{- end }}
