---
apiVersion: v1
kind: Service
metadata:
  name: readarr
  labels:
    app: readarr
    service: server
spec:
  selector:
    app: readarr
  ports:
    - protocol: TCP
      port: 8787
      targetPort: 8787
