---
apiVersion: v1
kind: Service
metadata:
  name: fluidd
  namespace: {{ .Release.Namespace }}
  labels:
    app: fluidd
    service: server
spec:
  type: ClusterIP
  selector:
    app: fluidd
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
