apiVersion: v1
kind: Service
metadata:
  name: server-{{ template "7dtd.fullname" . }}
  labels:
    app: {{ template "7dtd.name" . }}
    chart: {{ template "7dtd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: "{{ .Values.service.type }}"
  {{ with .Values.service.clusterIP }}clusterIP: {{ . | quote }}{{ end }}
  {{- if .Values.service.externalIPs }}
  externalIPs:
    {{- toYaml .Values.service.externalIPs | nindent 4 }}
  {{- end }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.service.loadBalancerIP }}"
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  ports:
    - name: 7dtd-tcp
      port: 26900
      protocol: TCP
      targetPort: 7dtd-tcp
      nodePort: 26900
    - name: 7dtd-udp
      port: 26900
      protocol: UDP
      targetPort: 7dtd-udp
      nodePort: 26900
    - name: 7dtd-udp2
      port: 26901
      protocol: UDP
      targetPort: 7dtd-udp2
      nodePort: 26901
    - name: 7dtd-udp3
      port: 26902
      protocol: UDP
      targetPort: 7dtd-udp2
      nodePort: 26902
    - name: 7dtd-webadmin
      port: 8080
      protocol: TCP
      targetPort: 7dtd-webadmin
    - name: 7dtd-telnet
      port: 8081
      protocol: TCP
      targetPort: 7dtd-telnet
    - name: 7dtd-http
      port: 8082
      protocol: TCP
      targetPort: 7dtd-http
  selector:
    app: {{ template "7dtd.name" . }}
    release: {{ .Release.Name }}
